Add more details to error messages

diff --git a/bin/status-disk b/bin/status-disk
--- a/bin/status-disk
+++ b/bin/status-disk
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=1.0.0
+VERSION=1.1.0
 
 USAGE=$(cat << EOF
 Usage: $(basename "${0}") [-hv] FRONTEND
@@ -42,7 +42,7 @@ done
 FRONTEND="${1}"
 
 if [ -z "${FRONTEND}" ] || [ "${FRONTEND}" != 'tmux' ] && [ "${FRONTEND}" != 'xfce' ]; then
-    echo "${0}: missing or invalid argument FRONTEND" >&2
+    echo "${0}: '${FRONTEND}': missing or invalid argument FRONTEND" >&2
     exit 1
 fi
 
@@ -118,6 +118,12 @@ fi
 # - Calculate disk size in an OS-agnostic way (replace `df -h` and `df -H` that
 #   depends on `uname`)?
 # - Allow to specify PARTITIONS via option?
+#
+# [1.1.0] - 2023-07-13
+#
+# CHANGED
+# - Print the value of ARGUMENT in `missing or invalid argument ARGUMENT` error
+#   messages.
 #
 # [1.0.0] - 2023-07-07
 #
diff --git a/bin/status-load-average b/bin/status-load-average
--- a/bin/status-load-average
+++ b/bin/status-load-average
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=1.0.0
+VERSION=1.1.0
 
 USAGE=$(cat << EOF
 Usage: $(basename "${0}") [-hv] FRONTEND
@@ -42,7 +42,7 @@ done
 FRONTEND="${1}"
 
 if [ -z "${FRONTEND}" ] || [ "${FRONTEND}" != 'tmux' ] && [ "${FRONTEND}" != 'xfce' ]; then
-    echo "${0}: missing or invalid argument FRONTEND" >&2
+    echo "${0}: '${FRONTEND}': missing or invalid argument FRONTEND" >&2
     exit 1
 fi
 
@@ -79,6 +79,12 @@ fi
 #
 # The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 # and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
+#
+# [1.1.0] - 2023-07-13
+#
+# CHANGED
+# - Print the value of ARGUMENT in `missing or invalid argument ARGUMENT` error
+#   messages.
 #
 # [1.0.0] - 2023-07-07
 #
diff --git a/bin/status-outdated-packages b/bin/status-outdated-packages
--- a/bin/status-outdated-packages
+++ b/bin/status-outdated-packages
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=2.1.1
+VERSION=2.2.0
 
 USAGE=$(cat << EOF
 Usage: $(basename "${0}") [-hv] PACKAGE_MANAGER FRONTEND
@@ -55,12 +55,12 @@ PACKAGE_MANAGER="${1}"
 FRONTEND="${2}"
 
 if [ -z "${PACKAGE_MANAGER}" ] || [ "${PACKAGE_MANAGER}" != 'brew' ] && [ "${PACKAGE_MANAGER}" != 'pacman' ]; then
-    echo "${0}: missing or invalid argument PACKAGE_MANAGER" >&2
+    echo "${0}: '${PACKAGE_MANAGER}': missing or invalid argument PACKAGE_MANAGER" >&2
     exit 1
 fi
 
 if [ -z "${FRONTEND}" ] || [ "${FRONTEND}" != 'tmux' ] && [ "${FRONTEND}" != 'xfce' ]; then
-    echo "${0}: missing or invalid argument FRONTEND" >&2
+    echo "${0}: '${FRONTEND}': missing or invalid argument FRONTEND" >&2
     exit 1
 fi
 
@@ -128,6 +128,12 @@ fi
 #
 # The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 # and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
+#
+# [2.2.0] - 2023-07-13
+#
+# CHANGED
+# - Print the value of ARGUMENT in `missing or invalid argument ARGUMENT` error
+#   messages.
 #
 # [2.1.1] - 2023-07-07
 #
